name: Build nuitka distribution

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    strategy:
      matrix:
        architecture: ['x86', 'x64']

    env:
      NUITKA_ASSUME_YES: 1
      NUITKA_COMPILER_USE_DEFAULT: 1

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: ${{ matrix.architecture }}

      # So much for the human readability
      - name: Generate variables
        id: vars
        working-directory: .github/workflows/
        run: python gen_build_vars.py ${{ matrix.architecture }}

      - name: Install wheel, nuitka and dependencies
        run: |
          pip install wheel
          pip install nuitka
          pip install -r requirements.txt

      - name: Build
        run: python setup_nuitka.py

      - name: Create and upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.vars.outputs.BUILD_NAME }}
          path: ${{ steps.vars.outputs.DEMOMGR_DIST_GLOB }}
