name: Build nuitka distribution

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    strategy:
      matrix:
        architecture: ['x86', 'x64']

    env:
      NUITKA_ASSUME_YES: 1
      NUITKA_COMPILER_USE_DEFAULT: 1

    runs-on: windows-latest

    steps:
      # So much for the human readability
      - name: Generate variables
        id: vars
        run: "
          (
          echo 'import os'
          echo 'import re'
          echo ''
          echo 'RE_SEMVER = re.compile('
          echo '  \"(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\"'
          echo '  \"(?:-((?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)\"'
          echo '  \"(?:\\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))\"'
          echo '  \"?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$\"'
          echo ')'
          echo 'arch = \"${{ matrix.architecture }}\"'
          echo 'dist_path = \"./nuitka_build/demomgr.dist\"'
          echo ''
          echo 'if (sv := RE_SEMVER.search(\"${{ github.ref }}\")) is None:'
          echo ' raise RuntimeError(\"Semver not found in github.ref!\")'
          echo ''
          echo 'build_name = f\"demomgr_v{sv[0]}_win{arch}\"'
          echo 'zip_path = f\"./nuitka_build/{build_name}.zip\"'
          echo 'for n, v in ('
          echo '  (\"BUILD_NAME\", \"DEMOMGR_DIST_ZIP_PATH\", \"DEMOMGR_DIST_PATH\"),'
          echo '  (build_name, zip_path, dist_path)'
          echo '):'
          echo '  print(f\"::set-output name={n}::{v}\")'
          ) | python
        "

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: ${{ matrix.architecture }}

      - name: Install wheel, nuitka and dependencies
        run: |
          pip install wheel
          pip install nuitka
          pip install -r requirements.txt

      - name: Build
        run: python setup_nuitka.py

      - name: Zip
        run: >
          7z a -tzip
          ${{ steps.vars.outputs.DEMOMGR_DIST_ZIP_PATH }}
          ${{ steps.vars.outputs.DEMOMGR_DIST_PATH }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.vars.outputs.BUILD_NAME }}
          path: ${{ steps.vars.outputs.DEMOMGR_DIST_ZIP_PATH }}
