name: Build nuitka distribution

on:
  push:
    branches: [ master ]
    tags: [ v* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    strategy:
      matrix:
        architecture: ['x86', 'x64']

    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: ${{ matrix.architecture }}

      - name: Install nutika
        run: pip install nuitka

      - name: Build
        run: python $GITHUB_WORKSPACE/setup_nuitka.py
